/*
 * Flight Offers Search
 *  Before using this API, we recommend you read our **[Authorization Guide](https://developers.amadeus.com/self-service/apis-docs/guides/authorization)** for more information on how to generate an access token.   Please also be aware that our test environment is based on a subset of the production, if you are not returning any results try with big cities/airports like LON (London) or NYC (New-York).
 *
 * OpenAPI spec version: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.BaggageAllowance;
import io.swagger.client.model.ServiceName;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * AdditionalServicesRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-09-05T13:16:41.117316-07:00[America/Hermosillo]")

public class AdditionalServicesRequest {
  @SerializedName("chargeableCheckedBags")
  private BaggageAllowance chargeableCheckedBags = null;

  @SerializedName("chargeableSeatNumber")
  private String chargeableSeatNumber = null;

  @SerializedName("otherServices")
  private List<ServiceName> otherServices = null;

  public AdditionalServicesRequest chargeableCheckedBags(BaggageAllowance chargeableCheckedBags) {
    this.chargeableCheckedBags = chargeableCheckedBags;
    return this;
  }

   /**
   * Get chargeableCheckedBags
   * @return chargeableCheckedBags
  **/
  @Schema(description = "")
  public BaggageAllowance getChargeableCheckedBags() {
    return chargeableCheckedBags;
  }

  public void setChargeableCheckedBags(BaggageAllowance chargeableCheckedBags) {
    this.chargeableCheckedBags = chargeableCheckedBags;
  }

  public AdditionalServicesRequest chargeableSeatNumber(String chargeableSeatNumber) {
    this.chargeableSeatNumber = chargeableSeatNumber;
    return this;
  }

   /**
   * seat number
   * @return chargeableSeatNumber
  **/
  @Schema(example = "33D", description = "seat number")
  public String getChargeableSeatNumber() {
    return chargeableSeatNumber;
  }

  public void setChargeableSeatNumber(String chargeableSeatNumber) {
    this.chargeableSeatNumber = chargeableSeatNumber;
  }

  public AdditionalServicesRequest otherServices(List<ServiceName> otherServices) {
    this.otherServices = otherServices;
    return this;
  }

  public AdditionalServicesRequest addOtherServicesItem(ServiceName otherServicesItem) {
    if (this.otherServices == null) {
      this.otherServices = new ArrayList<ServiceName>();
    }
    this.otherServices.add(otherServicesItem);
    return this;
  }

   /**
   * Other services to add
   * @return otherServices
  **/
  @Schema(example = "[\"PRIORITY_BOARDING\"]", description = "Other services to add")
  public List<ServiceName> getOtherServices() {
    return otherServices;
  }

  public void setOtherServices(List<ServiceName> otherServices) {
    this.otherServices = otherServices;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdditionalServicesRequest additionalServicesRequest = (AdditionalServicesRequest) o;
    return Objects.equals(this.chargeableCheckedBags, additionalServicesRequest.chargeableCheckedBags) &&
        Objects.equals(this.chargeableSeatNumber, additionalServicesRequest.chargeableSeatNumber) &&
        Objects.equals(this.otherServices, additionalServicesRequest.otherServices);
  }

  @Override
  public int hashCode() {
    return Objects.hash(chargeableCheckedBags, chargeableSeatNumber, otherServices);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdditionalServicesRequest {\n");
    
    sb.append("    chargeableCheckedBags: ").append(toIndentedString(chargeableCheckedBags)).append("\n");
    sb.append("    chargeableSeatNumber: ").append(toIndentedString(chargeableSeatNumber)).append("\n");
    sb.append("    otherServices: ").append(toIndentedString(otherServices)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
