/*
 * Flight Offers Search
 *  Before using this API, we recommend you read our **[Authorization Guide](https://developers.amadeus.com/self-service/apis-docs/guides/authorization)** for more information on how to generate an access token.   Please also be aware that our test environment is based on a subset of the production, if you are not returning any results try with big cities/airports like LON (London) or NYC (New-York).
 *
 * OpenAPI spec version: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.AircraftEquipment;
import io.swagger.client.model.FlightEndPoint;
import io.swagger.client.model.FlightStop;
import io.swagger.client.model.OperatingFlight;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * defining a flight segment; including both operating and marketing details when applicable
 */
@Schema(description = "defining a flight segment; including both operating and marketing details when applicable")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-09-05T13:16:41.117316-07:00[America/Hermosillo]")

public class FlightSegment {
  @SerializedName("aircraft")
  private AircraftEquipment aircraft = null;

  @SerializedName("arrival")
  private FlightEndPoint arrival = null;

  @SerializedName("carrierCode")
  private String carrierCode = null;

  @SerializedName("departure")
  private FlightEndPoint departure = null;

  @SerializedName("duration")
  private String duration = null;

  @SerializedName("number")
  private String number = null;

  @SerializedName("operating")
  private OperatingFlight operating = null;

  @SerializedName("stops")
  private List<FlightStop> stops = null;

  public FlightSegment aircraft(AircraftEquipment aircraft) {
    this.aircraft = aircraft;
    return this;
  }

   /**
   * Get aircraft
   * @return aircraft
  **/
  @Schema(description = "")
  public AircraftEquipment getAircraft() {
    return aircraft;
  }

  public void setAircraft(AircraftEquipment aircraft) {
    this.aircraft = aircraft;
  }

  public FlightSegment arrival(FlightEndPoint arrival) {
    this.arrival = arrival;
    return this;
  }

   /**
   * Get arrival
   * @return arrival
  **/
  @Schema(description = "")
  public FlightEndPoint getArrival() {
    return arrival;
  }

  public void setArrival(FlightEndPoint arrival) {
    this.arrival = arrival;
  }

  public FlightSegment carrierCode(String carrierCode) {
    this.carrierCode = carrierCode;
    return this;
  }

   /**
   * providing the airline / carrier code
   * @return carrierCode
  **/
  @Schema(example = "DL", description = "providing the airline / carrier code")
  public String getCarrierCode() {
    return carrierCode;
  }

  public void setCarrierCode(String carrierCode) {
    this.carrierCode = carrierCode;
  }

  public FlightSegment departure(FlightEndPoint departure) {
    this.departure = departure;
    return this;
  }

   /**
   * Get departure
   * @return departure
  **/
  @Schema(description = "")
  public FlightEndPoint getDeparture() {
    return departure;
  }

  public void setDeparture(FlightEndPoint departure) {
    this.departure = departure;
  }

  public FlightSegment duration(String duration) {
    this.duration = duration;
    return this;
  }

   /**
   * stop duration in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) PnYnMnDTnHnMnS format, e.g. PT2H10M
   * @return duration
  **/
  @Schema(example = "PT2H10M", description = "stop duration in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) PnYnMnDTnHnMnS format, e.g. PT2H10M")
  public String getDuration() {
    return duration;
  }

  public void setDuration(String duration) {
    this.duration = duration;
  }

  public FlightSegment number(String number) {
    this.number = number;
    return this;
  }

   /**
   * the flight number as assigned by the carrier
   * @return number
  **/
  @Schema(example = "212", description = "the flight number as assigned by the carrier")
  public String getNumber() {
    return number;
  }

  public void setNumber(String number) {
    this.number = number;
  }

  public FlightSegment operating(OperatingFlight operating) {
    this.operating = operating;
    return this;
  }

   /**
   * Get operating
   * @return operating
  **/
  @Schema(description = "")
  public OperatingFlight getOperating() {
    return operating;
  }

  public void setOperating(OperatingFlight operating) {
    this.operating = operating;
  }

  public FlightSegment stops(List<FlightStop> stops) {
    this.stops = stops;
    return this;
  }

  public FlightSegment addStopsItem(FlightStop stopsItem) {
    if (this.stops == null) {
      this.stops = new ArrayList<FlightStop>();
    }
    this.stops.add(stopsItem);
    return this;
  }

   /**
   * information regarding the different stops composing the flight segment. E.g. technical stop, change of gauge...
   * @return stops
  **/
  @Schema(description = "information regarding the different stops composing the flight segment. E.g. technical stop, change of gauge...")
  public List<FlightStop> getStops() {
    return stops;
  }

  public void setStops(List<FlightStop> stops) {
    this.stops = stops;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FlightSegment flightSegment = (FlightSegment) o;
    return Objects.equals(this.aircraft, flightSegment.aircraft) &&
        Objects.equals(this.arrival, flightSegment.arrival) &&
        Objects.equals(this.carrierCode, flightSegment.carrierCode) &&
        Objects.equals(this.departure, flightSegment.departure) &&
        Objects.equals(this.duration, flightSegment.duration) &&
        Objects.equals(this.number, flightSegment.number) &&
        Objects.equals(this.operating, flightSegment.operating) &&
        Objects.equals(this.stops, flightSegment.stops);
  }

  @Override
  public int hashCode() {
    return Objects.hash(aircraft, arrival, carrierCode, departure, duration, number, operating, stops);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FlightSegment {\n");
    
    sb.append("    aircraft: ").append(toIndentedString(aircraft)).append("\n");
    sb.append("    arrival: ").append(toIndentedString(arrival)).append("\n");
    sb.append("    carrierCode: ").append(toIndentedString(carrierCode)).append("\n");
    sb.append("    departure: ").append(toIndentedString(departure)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    operating: ").append(toIndentedString(operating)).append("\n");
    sb.append("    stops: ").append(toIndentedString(stops)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
