/*
 * Flight Offers Search
 *  Before using this API, we recommend you read our **[Authorization Guide](https://developers.amadeus.com/self-service/apis-docs/guides/authorization)** for more information on how to generate an access token.   Please also be aware that our test environment is based on a subset of the production, if you are not returning any results try with big cities/airports like LON (London) or NYC (New-York).
 *
 * OpenAPI spec version: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.FlightOfferSource;
import io.swagger.client.model.OriginDestination;
import io.swagger.client.model.SearchCriteria;
import io.swagger.client.model.Traveler;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * GetFlightOffersQuery
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-09-05T13:16:41.117316-07:00[America/Hermosillo]")

public class GetFlightOffersQuery {
  @SerializedName("currencyCode")
  private String currencyCode = null;

  @SerializedName("originDestinations")
  private List<OriginDestination> originDestinations = new ArrayList<OriginDestination>();

  @SerializedName("searchCriteria")
  private SearchCriteria searchCriteria = null;

  @SerializedName("sources")
  private List<FlightOfferSource> sources = new ArrayList<FlightOfferSource>();

  @SerializedName("travelers")
  private List<Traveler> travelers = new ArrayList<Traveler>();

  public GetFlightOffersQuery currencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
    return this;
  }

   /**
   * The currency code, as defined in [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217), to reflect the currency in which this amount is expressed.
   * @return currencyCode
  **/
  @Schema(example = "EUR", description = "The currency code, as defined in [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217), to reflect the currency in which this amount is expressed.")
  public String getCurrencyCode() {
    return currencyCode;
  }

  public void setCurrencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
  }

  public GetFlightOffersQuery originDestinations(List<OriginDestination> originDestinations) {
    this.originDestinations = originDestinations;
    return this;
  }

  public GetFlightOffersQuery addOriginDestinationsItem(OriginDestination originDestinationsItem) {
    this.originDestinations.add(originDestinationsItem);
    return this;
  }

   /**
   * Origins and Destinations must be properly ordered in time (chronological order in accordance with the timezone of each location) to describe the journey consistently. Dates and times must not be past nor more than 365 days in the future, according to provider settings.Number of Origins and Destinations must not exceed the limit defined in provider settings.
   * @return originDestinations
  **/
  @Schema(required = true, description = "Origins and Destinations must be properly ordered in time (chronological order in accordance with the timezone of each location) to describe the journey consistently. Dates and times must not be past nor more than 365 days in the future, according to provider settings.Number of Origins and Destinations must not exceed the limit defined in provider settings.")
  public List<OriginDestination> getOriginDestinations() {
    return originDestinations;
  }

  public void setOriginDestinations(List<OriginDestination> originDestinations) {
    this.originDestinations = originDestinations;
  }

  public GetFlightOffersQuery searchCriteria(SearchCriteria searchCriteria) {
    this.searchCriteria = searchCriteria;
    return this;
  }

   /**
   * Get searchCriteria
   * @return searchCriteria
  **/
  @Schema(description = "")
  public SearchCriteria getSearchCriteria() {
    return searchCriteria;
  }

  public void setSearchCriteria(SearchCriteria searchCriteria) {
    this.searchCriteria = searchCriteria;
  }

  public GetFlightOffersQuery sources(List<FlightOfferSource> sources) {
    this.sources = sources;
    return this;
  }

  public GetFlightOffersQuery addSourcesItem(FlightOfferSource sourcesItem) {
    this.sources.add(sourcesItem);
    return this;
  }

   /**
   * Allows enable one or more sources. If present in the list, these sources will be called by the system.
   * @return sources
  **/
  @Schema(required = true, description = "Allows enable one or more sources. If present in the list, these sources will be called by the system.")
  public List<FlightOfferSource> getSources() {
    return sources;
  }

  public void setSources(List<FlightOfferSource> sources) {
    this.sources = sources;
  }

  public GetFlightOffersQuery travelers(List<Traveler> travelers) {
    this.travelers = travelers;
    return this;
  }

  public GetFlightOffersQuery addTravelersItem(Traveler travelersItem) {
    this.travelers.add(travelersItem);
    return this;
  }

   /**
   * Get travelers
   * @return travelers
  **/
  @Schema(required = true, description = "")
  public List<Traveler> getTravelers() {
    return travelers;
  }

  public void setTravelers(List<Traveler> travelers) {
    this.travelers = travelers;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetFlightOffersQuery getFlightOffersQuery = (GetFlightOffersQuery) o;
    return Objects.equals(this.currencyCode, getFlightOffersQuery.currencyCode) &&
        Objects.equals(this.originDestinations, getFlightOffersQuery.originDestinations) &&
        Objects.equals(this.searchCriteria, getFlightOffersQuery.searchCriteria) &&
        Objects.equals(this.sources, getFlightOffersQuery.sources) &&
        Objects.equals(this.travelers, getFlightOffersQuery.travelers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currencyCode, originDestinations, searchCriteria, sources, travelers);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetFlightOffersQuery {\n");
    
    sb.append("    currencyCode: ").append(toIndentedString(currencyCode)).append("\n");
    sb.append("    originDestinations: ").append(toIndentedString(originDestinations)).append("\n");
    sb.append("    searchCriteria: ").append(toIndentedString(searchCriteria)).append("\n");
    sb.append("    sources: ").append(toIndentedString(sources)).append("\n");
    sb.append("    travelers: ").append(toIndentedString(travelers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
