/*
 * Flight Offers Search
 *  Before using this API, we recommend you read our **[Authorization Guide](https://developers.amadeus.com/self-service/apis-docs/guides/authorization)** for more information on how to generate an access token.   Please also be aware that our test environment is based on a subset of the production, if you are not returning any results try with big cities/airports like LON (London) or NYC (New-York).
 *
 * OpenAPI spec version: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * departure or arrival information
 */
@Schema(description = "departure or arrival information")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-09-05T13:16:41.117316-07:00[America/Hermosillo]")

public class OriginalFlightEndPoint {
  @SerializedName("iataCode")
  private String iataCode = null;

  @SerializedName("terminal")
  private String terminal = null;

  public OriginalFlightEndPoint iataCode(String iataCode) {
    this.iataCode = iataCode;
    return this;
  }

   /**
   * [IATA airline codes](http://www.iata.org/publications/Pages/code-search.aspx)
   * @return iataCode
  **/
  @Schema(example = "JFK", description = "[IATA airline codes](http://www.iata.org/publications/Pages/code-search.aspx)")
  public String getIataCode() {
    return iataCode;
  }

  public void setIataCode(String iataCode) {
    this.iataCode = iataCode;
  }

  public OriginalFlightEndPoint terminal(String terminal) {
    this.terminal = terminal;
    return this;
  }

   /**
   * terminal name / number
   * @return terminal
  **/
  @Schema(example = "T2", description = "terminal name / number")
  public String getTerminal() {
    return terminal;
  }

  public void setTerminal(String terminal) {
    this.terminal = terminal;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OriginalFlightEndPoint originalFlightEndPoint = (OriginalFlightEndPoint) o;
    return Objects.equals(this.iataCode, originalFlightEndPoint.iataCode) &&
        Objects.equals(this.terminal, originalFlightEndPoint.terminal);
  }

  @Override
  public int hashCode() {
    return Objects.hash(iataCode, terminal);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OriginalFlightEndPoint {\n");
    
    sb.append("    iataCode: ").append(toIndentedString(iataCode)).append("\n");
    sb.append("    terminal: ").append(toIndentedString(terminal)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
