/*
 * Flight Offers Search
 *  Before using this API, we recommend you read our **[Authorization Guide](https://developers.amadeus.com/self-service/apis-docs/guides/authorization)** for more information on how to generate an access token.   Please also be aware that our test environment is based on a subset of the production, if you are not returning any results try with big cities/airports like LON (London) or NYC (New-York).
 *
 * OpenAPI spec version: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.v3.oas.annotations.media.Schema;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * option specifying a group of fares, which may be valid under certain conditons Can be used to specify special fare discount for a passenger 
 */
@JsonAdapter(TravelerPricingFareOption.Adapter.class)
public enum TravelerPricingFareOption {
  @SerializedName("STANDARD")
  STANDARD("STANDARD"),
  @SerializedName("INCLUSIVE_TOUR")
  INCLUSIVE_TOUR("INCLUSIVE_TOUR"),
  @SerializedName("SPANISH_MELILLA_RESIDENT")
  SPANISH_MELILLA_RESIDENT("SPANISH_MELILLA_RESIDENT"),
  @SerializedName("SPANISH_CEUTA_RESIDENT")
  SPANISH_CEUTA_RESIDENT("SPANISH_CEUTA_RESIDENT"),
  @SerializedName("SPANISH_CANARY_RESIDENT")
  SPANISH_CANARY_RESIDENT("SPANISH_CANARY_RESIDENT"),
  @SerializedName("SPANISH_BALEARIC_RESIDENT")
  SPANISH_BALEARIC_RESIDENT("SPANISH_BALEARIC_RESIDENT"),
  @SerializedName("AIR_FRANCE_METROPOLITAN_DISCOUNT_PASS")
  AIR_FRANCE_METROPOLITAN_DISCOUNT_PASS("AIR_FRANCE_METROPOLITAN_DISCOUNT_PASS"),
  @SerializedName("AIR_FRANCE_DOM_DISCOUNT_PASS")
  AIR_FRANCE_DOM_DISCOUNT_PASS("AIR_FRANCE_DOM_DISCOUNT_PASS"),
  @SerializedName("AIR_FRANCE_COMBINED_DISCOUNT_PASS")
  AIR_FRANCE_COMBINED_DISCOUNT_PASS("AIR_FRANCE_COMBINED_DISCOUNT_PASS"),
  @SerializedName("AIR_FRANCE_FAMILY")
  AIR_FRANCE_FAMILY("AIR_FRANCE_FAMILY"),
  @SerializedName("ADULT_WITH_COMPANION")
  ADULT_WITH_COMPANION("ADULT_WITH_COMPANION"),
  @SerializedName("COMPANION")
  COMPANION("COMPANION");

  private String value;

  TravelerPricingFareOption(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static TravelerPricingFareOption fromValue(String input) {
    for (TravelerPricingFareOption b : TravelerPricingFareOption.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<TravelerPricingFareOption> {
    @Override
    public void write(final JsonWriter jsonWriter, final TravelerPricingFareOption enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public TravelerPricingFareOption read(final JsonReader jsonReader) throws IOException {
      Object value = jsonReader.nextString();
      return TravelerPricingFareOption.fromValue((String)(value));
    }
  }
}
