/*
 * Flight Offers Search
 *  Before using this API, we recommend you read our **[Authorization Guide](https://developers.amadeus.com/self-service/apis-docs/guides/authorization)** for more information on how to generate an access token.   Please also be aware that our test environment is based on a subset of the production, if you are not returning any results try with big cities/airports like LON (London) or NYC (New-York).
 *
 * OpenAPI spec version: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.TravelerType;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Traveler
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-09-05T13:16:41.117316-07:00[America/Hermosillo]")

public class Traveler {
  @SerializedName("associatedAdultId")
  private String associatedAdultId = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("travelerType")
  private TravelerType travelerType = null;

  public Traveler associatedAdultId(String associatedAdultId) {
    this.associatedAdultId = associatedAdultId;
    return this;
  }

   /**
   * if type&#x3D;\&quot;HELD_INFANT\&quot;, corresponds to the adult travelers&#x27;s id who will share the seat
   * @return associatedAdultId
  **/
  @Schema(description = "if type=\"HELD_INFANT\", corresponds to the adult travelers's id who will share the seat")
  public String getAssociatedAdultId() {
    return associatedAdultId;
  }

  public void setAssociatedAdultId(String associatedAdultId) {
    this.associatedAdultId = associatedAdultId;
  }

  public Traveler id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(example = "1", required = true, description = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Traveler travelerType(TravelerType travelerType) {
    this.travelerType = travelerType;
    return this;
  }

   /**
   * Get travelerType
   * @return travelerType
  **/
  @Schema(required = true, description = "")
  public TravelerType getTravelerType() {
    return travelerType;
  }

  public void setTravelerType(TravelerType travelerType) {
    this.travelerType = travelerType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Traveler traveler = (Traveler) o;
    return Objects.equals(this.associatedAdultId, traveler.associatedAdultId) &&
        Objects.equals(this.id, traveler.id) &&
        Objects.equals(this.travelerType, traveler.travelerType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(associatedAdultId, id, travelerType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Traveler {\n");
    
    sb.append("    associatedAdultId: ").append(toIndentedString(associatedAdultId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    travelerType: ").append(toIndentedString(travelerType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
