/*
 * Flight Offers Search
 *  Before using this API, we recommend you read our **[Authorization Guide](https://developers.amadeus.com/self-service/apis-docs/guides/authorization)** for more information on how to generate an access token.   Please also be aware that our test environment is based on a subset of the production, if you are not returning any results try with big cities/airports like LON (London) or NYC (New-York).
 *
 * OpenAPI spec version: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.v3.oas.annotations.media.Schema;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * traveler type age restrictions : CHILD &lt; 12y, HELD_INFANT &lt; 2y, SEATED_INFANT &lt; 2y, SENIOR &gt;&#x3D;60y 
 */
@JsonAdapter(TravelerType.Adapter.class)
public enum TravelerType {
  @SerializedName("ADULT")
  ADULT("ADULT"),
  @SerializedName("CHILD")
  CHILD("CHILD"),
  @SerializedName("SENIOR")
  SENIOR("SENIOR"),
  @SerializedName("YOUNG")
  YOUNG("YOUNG"),
  @SerializedName("HELD_INFANT")
  HELD_INFANT("HELD_INFANT"),
  @SerializedName("SEATED_INFANT")
  SEATED_INFANT("SEATED_INFANT"),
  @SerializedName("STUDENT")
  STUDENT("STUDENT");

  private String value;

  TravelerType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static TravelerType fromValue(String input) {
    for (TravelerType b : TravelerType.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<TravelerType> {
    @Override
    public void write(final JsonWriter jsonWriter, final TravelerType enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public TravelerType read(final JsonReader jsonReader) throws IOException {
      Object value = jsonReader.nextString();
      return TravelerType.fromValue((String)(value));
    }
  }
}
