/*
 * Flight Offers Search
 *  Before using this API, we recommend you read our **[Authorization Guide](https://developers.amadeus.com/self-service/apis-docs/guides/authorization)** for more information on how to generate an access token.   Please also be aware that our test environment is based on a subset of the production, if you are not returning any results try with big cities/airports like LON (London) or NYC (New-York).
 *
 * OpenAPI spec version: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.Error400;
import io.swagger.client.model.Error500;
import io.swagger.client.model.GetFlightOffersQuery;
import org.threeten.bp.LocalDate;
import io.swagger.client.model.Success;
import io.swagger.client.model.Success1;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for ShoppingApi
 */
@Ignore
public class ShoppingApiTest {

    private final ShoppingApi api = new ShoppingApi();

    /**
     * Return list of Flight Offers based on searching criteria.
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getFlightOffersTest() throws Exception {
        String originLocationCode = null;
        String destinationLocationCode = null;
        LocalDate departureDate = null;
        Integer adults = null;
        LocalDate returnDate = null;
        Integer children = null;
        Integer infants = null;
        String travelClass = null;
        String includedAirlineCodes = null;
        String excludedAirlineCodes = null;
        Boolean nonStop = null;
        String currencyCode = null;
        Integer maxPrice = null;
        Integer max = null;
        Success response = api.getFlightOffers(originLocationCode, destinationLocationCode, departureDate, adults, returnDate, children, infants, travelClass, includedAirlineCodes, excludedAirlineCodes, nonStop, currencyCode, maxPrice, max);

        // TODO: test validations
    }
    /**
     * Return list of Flight Offers based on posted searching criteria.
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void searchFlightOffersTest() throws Exception {
        GetFlightOffersQuery body = null;
        String xHTTPMethodOverride = null;
        Success1 response = api.searchFlightOffers(body, xHTTPMethodOverride);

        // TODO: test validations
    }
}
