/*
 * Airport & City Search
 *  Before using this API, we recommend you read our **[Authorization Guide](https://developers.amadeus.com/self-service/apis-docs/guides/authorization-262)** for more information on how to generate an access token.   Please also be aware that our test environment is based on a subset of the production, in test this API only contains data from the United States, Spain, United Kingdom, Germany and India. 
 *
 * OpenAPI spec version: 1.2.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.city;

import io.swagger.city.Error400;
import io.swagger.city.Error404;
import io.swagger.city.Error500;
import io.swagger.city.Success;
import io.swagger.city.Success1;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for LocationApi
 */
@Ignore
public class LocationApiTest {

    private final LocationApi api = new LocationApi();

    /**
     * Returns a specific airports or cities based on its id.
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getAirportCityTest() throws Exception {
        String locationId = null;
        Success1 response = api.getAirportCity(locationId);

        // TODO: test validations
    }
    /**
     * Returns a list of airports and cities matching a given keyword.
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getAirportCitySearchTest() throws Exception {
        List<String> subType = new ArrayList<>();

        subType.add("CITY");
        subType.add("AIRPORT");


        String keyword = "BKK";
        String countryCode = "TH";
        Integer pageLimit = null;
        Integer pageOffset = null;
        String sort = null;
        String view = "LIGHT";
        Success response = api.getAirportCitySearch(subType, keyword, countryCode, pageLimit, pageOffset, sort, view);

        System.out.println(response.getData());

        // TODO: test validations
    }
}
